#!/usr/bin/env python3

import shlex
import subprocess
import sys

args = ['bitcoin-cli']
args += sys.argv[1:]
args = shlex.join(args)
args = ['flatpak', 'run', '--command=sh', 'org.bitcoincore.bitcoin-qt', '-c', args]

sys.exit(subprocess.run(args).returncode)
