#!/usr/bin/env python3

import shlex
import subprocess
import sys

args = ['/app/bin/internal/test_bitcoin']
args += sys.argv[1:]
args = shlex.join(args)
args = ['flatpak', 'run', '--command=sh', 'org.bitcoincore.bitcoin-qt', '-c', args]

subprocess.run(args, check=True)
