container:
  cpu: 2
  memory: 8G
  greedy: true
timeout_in: 120m
env:
  TEST_RUNNER_PORT_MIN: "14000"  # Must be larger than 12321, which is used for the http cache. See https://cirrus-ci.org/guide/writing-tasks/#http-cache
  DEBIAN_FRONTEND: "noninteractive"
task:
  name: "Windows [gitian]"
  windows_container:
    image: cirrusci/windowsservercore:2019
  env:
    CIRRUS_SHELL: powershell
    PATH: 'C:\Python37;C:\Python37\Scripts;%PATH%'
    PYTHONUTF8: 1
    PYTHONIOENCODING: 'UTF-8'
    SHASUM: 'sha256sum'
  install_script:
    - choco install python --version=3.7.7 -y
    - powershell "python --version"
    - powershell 'C:\Python37\Scripts\pip install pyzmq'
  download_script:
    - git clone https://github.com/bitcoin/bitcoin.git ./bitcoin-core-nightly
    - cd bitcoin-core-nightly
    - set SRCDIR=$(pwd)
    - echo $SRCDIR
    - powershell "python ../download_latest_nightly.py --bin=WIN --srcdir=${SRCDIR}"
    - set VERSION=$(tail -1 ./version.txt)
    - set BUILDDIR=$(tail -1 ./build_dir.txt)
    - echo $VERSION
    - echo $BUILDDIR
#   script:
#    - ${BUILDDIR}/src/test_bitcoin.exe
#    - cd ${SRCDIR}
#    - git checkout $VERSION
#    - powershell "${PYTHON} ./test/util/bitcoin-util-test.py -v"
#    - powershell "${PYTHON} ./test/functional/test_runner.py --timeout-factor=10"
#after_script:
#    - cd ${SRCDIR}
#    - git log -1
#    - cd ${BUILDDIR}
#    - $SHASUM ./src/*
task:
  name: "FreeBSD 13.1 [system libs]"
  freebsd_instance:
    image_family: freebsd-13-1  # https://cirrus-ci.org/guide/FreeBSD/
  env:
    MAKEJOBS: "-j4"
    CONFIGURE_OPTS: "--disable-dependency-tracking --enable-suppress-external-warnings"
    CCACHE_SIZE: "200M"
    CCACHE_COMPRESS: 1
    CCACHE_DIR: "/tmp/ccache_dir"
  ccache_cache:
    folder: "/tmp/ccache_dir"
  install_script:
    - pkg install -y m4 autoconf automake boost-libs git gmake libevent libtool pkgconf python3 ccache sqlite3 databases/py-sqlite3
    - ccache --max-size=${CCACHE_SIZE}
    - git clone https://github.com/stewartsmith/libeatmydata.git
    - cd libeatmydata
    - autoreconf -i
    - ./configure
    - sed -i -e 's/O_DSYNC/O_SYNC/g' $(git grep -l O_DSYNC)
    - make
    - make install  # eatmydata
  upstream_clone_script:
    - git clone https://github.com/bitcoin/bitcoin --depth=1 ./bitcoin-core
    - cd bitcoin-core
    - gmake -C depends NO_BOOST=1 NO_LIBEVENT=1 NO_QT=1 NO_SQLITE=1 NO_NATPMP=1 NO_UPNP=1 NO_ZMQ=1 NO_USDT=1
  configure_script:
    - cd bitcoin-core
    - ./autogen.sh
    - ./configure ${CONFIGURE_OPTS} BDB_LIBS="-L$(pwd)/depends/$(./depends/config.guess)/lib -ldb_cxx-4.8" BDB_CFLAGS="-I$(pwd)/depends/$(./depends/config.guess)/include" || ( cat config.log && false)
  make_script:
    - cd bitcoin-core
    - gmake ${MAKEJOBS} || ( echo "Build failure. Verbose build follows." && gmake V=1 ; false )
  check_script:
    - cd bitcoin-core
    - gmake check ${MAKEJOBS} VERBOSE=1
  functional_test_script:
    - cd bitcoin-core
    - eatmydata ./test/functional/test_runner.py $MAKEJOBS --ci --extended --exclude feature_block,feature_dbcrash,p2p_timeouts --combinedlogslen=19999000 --quiet --failfast --timeout-factor=10
task:
  name: "OpenSuse Tumbleweed [system libs]"
  container:
    image: opensuse/tumbleweed
  env:
    MAKEJOBS: "-j6"
    TEST_RUNNER_PORT_MIN: "14000"  # Must be larger than 12321, which is used for the http cache. See https://cirrus-ci.org/guide/writing-tasks/#http-cache
    CCACHE_SIZE: "200M"
    CCACHE_DIR: "/tmp/ccache_dir"
  ccache_cache:
    folder: "/tmp/ccache_dir"
  install_script:
    - zypper --non-interactive install -t pattern devel_basis
    - zypper --non-interactive install git libtool pkg-config automake python3 libevent-devel libboost_headers-devel gcc-c++ ccache zeromq-devel libqt5-qtbase-devel libqt5-qttools-devel qrencode-devel sqlite3-devel
    - ccache --max-size=${CCACHE_SIZE}
  upstream_clone_script:
    - git clone https://github.com/bitcoin/bitcoin --depth=1 ./bitcoin-core
  configure_script:
    - cd bitcoin-core
    - ./autogen.sh
    - ./configure || ( cat config.log && false)
  make_script:
    - cd bitcoin-core
    - make ${MAKEJOBS} || ( echo "Build failure. Verbose build follows." && make V=1 ; false )
  check_script:
    - cd bitcoin-core
    - make check ${MAKEJOBS} VERBOSE=1
  functional_test_script:
    - cd bitcoin-core
    - ./test/functional/test_runner.py $MAKEJOBS --ci --extended --combinedlogslen=199999000 --quiet --failfast --timeout-factor=3
task:
  name: "CentOS 8 [system libs]"
  container:
    image: quay.io/centos/centos:stream8
  env:
    MAKEJOBS: "-j6"
    TEST_RUNNER_PORT_MIN: "14000"  # Must be larger than 12321, which is used for the http cache. See https://cirrus-ci.org/guide/writing-tasks/#http-cache
    CCACHE_SIZE: "200M"
    CCACHE_DIR: "/tmp/ccache_dir"
  ccache_cache:
    folder: "/tmp/ccache_dir"
  install_script:
    - dnf -y install epel-release
    - dnf install -y ccache gcc-c++ libtool make git python38 python38-pip boost-devel libevent-devel sqlite-devel zeromq-devel qt5-qtbase-devel qt5-qttools-devel # disabled for now: bdb, qrencode-devel, upnp
    - pip3 install zmq
    - ccache --max-size=${CCACHE_SIZE}
  upstream_clone_script:
    - git clone https://github.com/bitcoin/bitcoin --depth=1 ./bitcoin-core
  configure_script:
    - cd bitcoin-core
    - ./autogen.sh
    - ./configure --with-incompatible-bdb || ( cat config.log && false)
  make_script:
    - cd bitcoin-core
    - make ${MAKEJOBS} || ( echo "Build failure. Verbose build follows." && make V=1 ; false )
  check_script:
    - cd bitcoin-core
    - make check ${MAKEJOBS} VERBOSE=1
  functional_test_script:
    - cd bitcoin-core
    - ./test/functional/test_runner.py $MAKEJOBS --ci --extended --combinedlogslen=199999000 --quiet --failfast --timeout-factor=3
task:
  container:
    image: debian:experimental
    cpu: 4
    memory: 16G
    greedy: true
  env:
    MAKEJOBS: "-j9"
    TEST_RUNNER_PORT_MIN: "14000"  # Must be larger than 12321, which is used for the http cache. See https://cirrus-ci.org/guide/writing-tasks/#http-cache
    CCACHE_SIZE: "200M"
    CCACHE_DIR: "/tmp/ccache_dir"
  ccache_cache:
    folder: "/tmp/ccache_dir"
  install_script:
    - apt update && apt -t experimental install -y git ccache build-essential libtool autotools-dev automake pkg-config bsdmainutils python3-zmq libevent-dev libboost-dev qttools5-dev qttools5-dev-tools systemtap-sdt-dev libminiupnpc-dev libnatpmp-dev libqrencode-dev libzmq3-dev
    - ccache --max-size=${CCACHE_SIZE}
  upstream_clone_script:
    - git clone https://github.com/bitcoin/bitcoin --depth=1 ./bitcoin-core
    - cd bitcoin-core
    - ./autogen.sh
  matrix:
    - name: "debian:experimental [system libs, asan, clang, sqlite-only, libc++]"
      install_matrix_script:
        - apt -t experimental install -y libc++abi-dev libc++-dev clang llvm libsqlite3-dev
        - cd bitcoin-core
        - ./configure --with-sanitizers=address,integer,undefined CC=clang CXX="clang++ -stdlib=libc++" || ( cat config.log && false)
    - name: "debian:experimental [system libs, asan, clang, sqlite-only]"
      install_matrix_script:
        - apt -t experimental install -y clang llvm libsqlite3-dev
        - cd bitcoin-core
        - ./configure --with-sanitizers=address,integer,undefined CC=clang CXX="clang++" || ( cat config.log && false)
    - name: "debian:experimental [system libs, asan, gcc, bdb-only]"
      install_matrix_script:
        - apt -t experimental install -y libdb++-dev
        - cd bitcoin-core
        - echo 'nonnull-attribute:streams.h' >> test/sanitizer_suppressions/ubsan  # runtime error: null pointer passed as argument 1, which is declared to never be null, fwrite
        - ./configure --with-sanitizers=address,undefined --with-incompatible-bdb || ( cat config.log && false)
    - name: "debian:experimental [system libs, tsan, clang, sqlite-only, libc++]"
      install_matrix_script:
        - apt -t experimental install -y libc++abi-dev libc++-dev clang llvm libsqlite3-dev
        - cd bitcoin-core
        - ./configure --with-sanitizers=thread CC=clang CXX="clang++ -stdlib=libc++" || ( cat config.log && false)
    - name: "debian:experimental [system libs, tsan, clang, sqlite-only]"
      install_matrix_script:
        - apt -t experimental install -y clang llvm libsqlite3-dev
        - cd bitcoin-core
        - ./configure --with-sanitizers=thread CC=clang CXX="clang++" || ( cat config.log && false)
    - name: "debian:experimental [system libs, tsan, gcc, bdb-only]"
      install_matrix_script:
        - apt -t experimental install -y libdb++-dev
        - cd bitcoin-core
        - echo 'race:libQt5Core' >> test/sanitizer_suppressions/tsan
        - ./configure --with-sanitizers=thread --with-incompatible-bdb || ( cat config.log && false)
  make_script:
    - cd bitcoin-core
    - make ${MAKEJOBS} ${GOAL} || ( echo "Build failure. Verbose build follows." && make ${GOAL} V=1 ; false )
  check_script:
    - cd bitcoin-core
    - export LSAN_OPTIONS="suppressions=$(pwd)/test/sanitizer_suppressions/lsan"
    - export TSAN_OPTIONS="suppressions=$(pwd)/test/sanitizer_suppressions/tsan:halt_on_error=1"
    - export UBSAN_OPTIONS="suppressions=$(pwd)/test/sanitizer_suppressions/ubsan:print_stacktrace=1:halt_on_error=1"
    - make check ${MAKEJOBS} VERBOSE=1
    - ./test/functional/test_runner.py $MAKEJOBS --exclude feature_dbcrash --extended --combinedlogslen=199999000 --quiet --failfast --timeout-factor=9
task:
  name: "Alpine [system libs]"
  container:
    image: alpine:latest
  env:
    LC_ALL: "C"
    MAKEJOBS: "-j8"
    TEST_RUNNER_PORT_MIN: "14000"  # Must be larger than 12321, which is used for the http cache. See https://cirrus-ci.org/guide/writing-tasks/#http-cache
    CCACHE_SIZE: "200M"
    CCACHE_DIR: "/tmp/ccache_dir"
  ccache_cache:
    folder: "/tmp/ccache_dir"
  install_script:
    - apk --no-cache --update add autoconf automake g++ gcc git libtool make pkgconfig python3 boost-dev libevent-dev zeromq-dev qt5-qtbase-dev qt5-qttools-dev ccache
    - ccache --max-size=${CCACHE_SIZE}
  upstream_clone_script:
    - git clone https://github.com/bitcoin/bitcoin --depth=1 ./bitcoin-core
  configure_script:
    - cd bitcoin-core
    - ./autogen.sh
    - ./configure || ( cat config.log && false)
  make_script:
    - cd bitcoin-core
    - make ${MAKEJOBS} || ( echo "Build failure. Verbose build follows." && make V=1 ; false )
  check_script:
    - cd bitcoin-core
    - make check ${MAKEJOBS} VERBOSE=1
  functional_test_script:
    - cd bitcoin-core
    - ./test/functional/test_runner.py $MAKEJOBS --ci --extended --combinedlogslen=199999000 --quiet --failfast --timeout-factor=3
task:
  name: "Arch [system libs]"
  container:
    image: archlinux:latest
  env:
    MAKEJOBS: "-j8"
    TEST_RUNNER_PORT_MIN: "14000"  # Must be larger than 12321, which is used for the http cache. See https://cirrus-ci.org/guide/writing-tasks/#http-cache
    CCACHE_SIZE: "200M"
    CCACHE_DIR: "/tmp/ccache_dir"
  ccache_cache:
    folder: "/tmp/ccache_dir"
  install_script:
    - pacman --noconfirm -Syu autoconf automake git gcc libtool make pkg-config python3 boost libevent zeromq ccache qt5
    - ccache --max-size=${CCACHE_SIZE}
  upstream_clone_script:
    - git clone https://github.com/bitcoin/bitcoin --depth=1 ./bitcoin-core
  configure_script:
    - cd bitcoin-core
    - ./autogen.sh
    - ./configure || ( cat config.log && false)
  make_script:
    - cd bitcoin-core
    - make ${MAKEJOBS} || ( echo "Build failure. Verbose build follows." && make V=1 ; false )
  check_script:
    - cd bitcoin-core
    - make check ${MAKEJOBS} VERBOSE=1
  functional_test_script:
    - cd bitcoin-core
    - ./test/functional/test_runner.py $MAKEJOBS --ci --extended --combinedlogslen=199999000 --quiet --failfast --timeout-factor=3
task:
  name: "s390x qemu"
  container:
    image: debian:bookworm
    cpu: 4
    memory: 10G
    greedy: true
  env:
    FILE_ENV: "./ci/test/00_setup_env_s390x.sh"
    MAKEJOBS: "-j10"
    DANGER_RUN_CI_ON_HOST: "1"
    TEST_RUNNER_PORT_MIN: "14000"  # Must be larger than 12321, which is used for the http cache. See https://cirrus-ci.org/guide/writing-tasks/#http-cache
    CCACHE_SIZE: "200M"
    CCACHE_DIR: "/tmp/ccache_dir"
  ccache_cache:
    folder: "/tmp/ccache_dir"
  upstream_clone_script:
    - apt update && apt install git -y
    - git clone https://github.com/bitcoin/bitcoin --depth=1 ./bitcoin-core
    - cd bitcoin-core
  ci_script:
    - cd bitcoin-core
    - ./ci/test_run_all.sh
task:
  name: "valgrind, system libs [ubuntu:devel]"
  container:
    image: ubuntu:devel  # valgrind supp is for bionic/focal, but use 22.04+ (devel) to avoid std::optional false-positive
    cpu: 4
    memory: 16G  # valgrind needs a lot of memory
    greedy: true
  env:
    FILE_ENV: "./ci/test/00_setup_env_native_valgrind.sh"
    MAKEJOBS: "-j12"
    DANGER_RUN_CI_ON_HOST: "1"
    TEST_RUNNER_PORT_MIN: "14000"  # Must be larger than 12321, which is used for the http cache. See https://cirrus-ci.org/guide/writing-tasks/#http-cache
    CCACHE_SIZE: "200M"
    CCACHE_DIR: "/tmp/ccache_dir"
  ccache_cache:
    folder: "/tmp/ccache_dir"
  upstream_clone_script:
    - apt update && apt install git -y
    - git clone https://github.com/bitcoin/bitcoin --depth=1 ./bitcoin-core
    - cd bitcoin-core
  ci_script:
    - cd bitcoin-core
    - ./ci/test_run_all.sh
task:
  name: "Fedora [system libs]"
  container:
    image: fedora:rawhide
  env:
    CCACHE_SIZE: "200M"
    CCACHE_DIR: "/tmp/ccache_dir"
  ccache_cache:
    folder: "/tmp/ccache_dir"
  upstream_clone_script:
    - dnf install git -y
    - git clone https://github.com/bitcoin/bitcoin --depth=1 ./bitcoin-core
  install_pkgs_script:
    - dnf install ccache gcc-c++ libtool make autoconf automake libevent-devel boost-devel libdb-cxx-devel python3 qt5-qttools-devel qt5-qtbase-devel sqlite-devel qrencode-devel systemtap zeromq-devel miniupnpc-devel libnatpmp-devel -y
  build_script:
    - cd bitcoin-core
    - ./autogen.sh && ./configure --enable-suppress-external-warnings --with-incompatible-bdb
    - make -j 9
  test_script:
    - cd bitcoin-core
    - make -j 9 check
    - ./test/functional/test_runner.py -j 9 --timeout-factor=5
## Disabled due to https://github.com/google/sanitizers/issues/1076
#   Location is global '__TMC_END__' at 0x55960bb18a48 (fuzz+0x000001984a51)
#  SUMMARY: ThreadSanitizer: data race src/logging.cpp:18 in LogInstance()
#task:
#  name: "fedora [system libs, fuzz, tsan]"
#  container:
#    image: fedora:rawhide
#  env:
#    CCACHE_SIZE: "200M"
#    CCACHE_DIR: "/tmp/ccache_dir"
#  ccache_cache:
#    folder: "/tmp/ccache_dir"
#  upstream_clone_script:
#    - dnf install git -y
#    - git clone https://github.com/bitcoin/bitcoin --depth=1 ./bitcoin-core
#    - git clone https://github.com/bitcoin-core/qa-assets --depth=1
#  install_pkgs_script:
#    - dnf install gcc-c++ libtool make autoconf automake libevent-devel boost-devel libdb-cxx-devel python3 clang qt5-qttools-devel qt5-qtbase-devel -y
#  ci_script:
#    - cd bitcoin-core
#    - ./autogen.sh && ./configure --with-sanitizers=fuzzer,thread --enable-fuzz --with-incompatible-bdb CC=clang CXX=clang++
#    - make -j 4
#  tsan_test_script:
#    - cd bitcoin-core
#    - export LSAN_OPTIONS="suppressions=$(pwd)/test/sanitizer_suppressions/lsan"
#    - export TSAN_OPTIONS="suppressions=$(pwd)/test/sanitizer_suppressions/tsan:halt_on_error=1"
#    - export UBSAN_OPTIONS="suppressions=$(pwd)/test/sanitizer_suppressions/ubsan:print_stacktrace=1:halt_on_error=1"
#    - ./test/fuzz/test_runner.py -j 4 -l DEBUG ../qa-assets/fuzz_seed_corpus/
task:
  name: "fuzz, asan, system libs [fedora]"
  container:
    image: fedora:rawhide
    cpu: 4
    memory: 8G
    greedy: true
  env:
    CCACHE_SIZE: "200M"
    CCACHE_DIR: "/tmp/ccache_dir"
  ccache_cache:
    folder: "/tmp/ccache_dir"
  upstream_clone_script:
    - dnf install git -y
    - git clone https://github.com/bitcoin/bitcoin --depth=1 ./bitcoin-core
    - git clone https://github.com/bitcoin-core/qa-assets --depth=1
  install_pkgs_script:
    - dnf install gcc-c++ libtool make autoconf automake libevent-devel boost-devel libdb-cxx-devel python3 clang qt5-qttools-devel qt5-qtbase-devel -y
  ci_script:
    - cd bitcoin-core
    - ./autogen.sh && ./configure --with-sanitizers=fuzzer,address,integer,undefined --enable-fuzz --with-incompatible-bdb CC=clang CXX=clang++
    - make -j 8
  tsan_test_script:
    - cd bitcoin-core
    - export LSAN_OPTIONS="suppressions=$(pwd)/test/sanitizer_suppressions/lsan"
    - export TSAN_OPTIONS="suppressions=$(pwd)/test/sanitizer_suppressions/tsan:halt_on_error=1"
    - export UBSAN_OPTIONS="suppressions=$(pwd)/test/sanitizer_suppressions/ubsan:print_stacktrace=1:halt_on_error=1"
    - ./test/fuzz/test_runner.py -j 8 -l DEBUG ../qa-assets/fuzz_seed_corpus/
task:
  name: "fuzz, system libs, enable debug [ubuntu:devel]"
  container:
    image: ubuntu:devel
  env:
    FILE_ENV: "./ci/test/00_setup_env_native_fuzz_enable_debug.sh"
    MAKEJOBS: "-j8"
    DANGER_RUN_CI_ON_HOST: "1"
    CCACHE_SIZE: "200M"
    CCACHE_DIR: "/tmp/ccache_dir"
  ccache_cache:
    folder: "/tmp/ccache_dir"
  upstream_clone_script:
    - apt update && apt install git -y
    - git clone https://github.com/bitcoin/bitcoin --depth=1 ./bitcoin-core
    - cd bitcoin-core
    - mv ../00_setup_env_native_fuzz_enable_debug.sh ./ci/test/
  ci_script:
    - cd bitcoin-core
    - ./ci/test_run_all.sh
task:
  name: "fuzz, depends DEBUG [ubuntu:devel]"
  container:
    image: ubuntu:devel
  env:
    CCACHE_SIZE: "200M"
    CCACHE_DIR: "/tmp/ccache_dir"
  ccache_cache:
    folder: "/tmp/ccache_dir"
  upstream_clone_script:
    - apt update && apt install git -y
    - git clone https://github.com/bitcoin/bitcoin --depth=1 ./bitcoin-core
    - git clone https://github.com/bitcoin-core/qa-assets --depth=1
  install_pkgs_script:
    - apt update && apt install curl wget htop git vim ccache llvm clang  build-essential libtool autotools-dev automake pkg-config bsdmainutils -y
  depends_script:
    - cd bitcoin-core
    - cd depends
    - make DEBUG=1 NO_QT=1 NO_WALLET=1 NO_ZMQ=1 NO_UPNP=1 NO_NATPMP=1 -j 4
  fuzz_build_script:
    - cd bitcoin-core
    - ./autogen.sh && CC=clang CXX=clang++ CONFIG_SITE="$PWD/depends/x86_64-pc-linux-gnu/share/config.site" ./configure --enable-fuzz --enable-debug --with-sanitizers=fuzzer
    - make -j 8
  fuzz_run_script:
    - cd bitcoin-core
    - ./test/fuzz/test_runner.py -j 8 -l DEBUG ../qa-assets/fuzz_seed_corpus/
